### ISSUE TITLE
Create the continuous integration

### ISSUE THREAD

**Issue by Thomaltarix** [Thomaltarix/Arrrrrcade#2]
# :white_check_mark: What's needed
The continuous integration must be created by github actions.
They must check the code quality using the Epitech standard rules for coding.
Then try to compile the project and run the tests.
If all these tests passes, then the actions must mirror to the official Epitech repository

## 📋 Subtasks
- [x] Check the code quality
- [x] Compile the project
- [x] Run the tests
- [x] Mirror the repository

## :file_folder: Files required
- [x] `checker.yml`
- [x] `mirror.yml`
