### ISSUE TITLE
Create the Menu

### ISSUE THREAD

**Issue by mathieurobert1** [Thomaltarix/Arrrrrcade#42]
# :white_check_mark: What's needed
Create the Menu (with IGame)

## 📋 Subtasks
- [x] launch at the beginning
- [x] display graphics libs
- [x] display games libs
- [ ] display scores
- [x] username space
- [x] start game

## :file_folder: Files required
src/include/IGame
