### ISSUE TITLE
Update Shared repository changes

### ISSUE THREAD

**Issue by mathieurobert1** [Thomaltarix/Arrrrrcade#55]
# :white_check_mark: What's needed
Update the changes of the shared repo

## 📋 Subtasks
- [x] rename file keys by Keys
- [x] fix entrypoint by raw pointer instead of uniques
- [x] add getter and setter in IGame
