### ISSUE TITLE
DLLoader class

### ISSUE THREAD

**Issue by mathieurobert1** [Thomaltarix/Arrrrrcade#9]
# :white_check_mark: What's needed
Create the DLLoader class to load the .so files
The class must contain:
- [x] A constructor which closes the actual .so file if opened
- [x] A destructor which closes the actual .so file
- [x] A `getInstance` method which takes a interface template as parameter an returns an Instance of the desired Interface 
- [x] A variable which store the opened file.

## 📋 Subtasks
This class must use:
- [x] dlopen
- [x] dlsym
- [x] dlclose
- [x] dlerror
